uktrade/terraform-platform-modules

.checkov.baseline
=> feat: 872 checkov baseline file

postgres/tests/unit.tftest.hcl
- Add tests to check that RDS instance can be configured with non default values in terraform
=> test: Add tests for non default values for RDS

s3/locals.tf, s3/tests/unit.tftest.hcl
- Fix kms key alias name format to include the application & environment also.
=> fix: Dbtp 1016 update kms key alias name

environment-pipelines/iam.tf, environment-pipelines/locals.tf, environment-pipelines/stage_config.yml, environment-pipelines/tests/unit.tftest.hcl
- Move extension IAM policies to managed policies to fix max policy size error
- Make pipeline output artifacts unique per environment
=> fix: DBTP-998 - Move pipeline to platform-sandbox

.checkov.baseline, application-load-balancer/main.tf, elasticache-redis/main.tf, elasticache-redis/tests/unit.tftest.hcl
Reverts uktrade/terraform-platform-modules#134
Because it's not actually breaking any more.
=> revert: "fix!: DBTP-944 remove "_ENDPOINT" from elasticache redis ssm parameter endpoint"

elasticache-redis/e2e-tests/e2e.tftest.hcl, elasticache-redis/locals.tf, elasticache-redis/main.tf, elasticache-redis/tests/unit.tftest.hcl
Address issues found during regression testing with @tony-griffin.
Then we pulled in the changes from https://github.com/uktrade/terraform-platform-modules/pull/133 because it's all related.
=> fix: DBTP-944 Correct Redis tags & DBTP-434 Add Redis endpoint with ssl_cert_reqs parameter

application-load-balancer/locals.tf, cdn/variables.tf, environment-pipelines/buildspec-apply.yml, environment-pipelines/buildspec-plan.yml, environment-pipelines/buildspec.yml, environment-pipelines/codepipeline.tf, environment-pipelines/iam.tf, environment-pipelines/locals.tf, environment-pipelines/tests/unit.tftest.hcl, environment-pipelines/variables.tf, s3/locals.tf
This PR adds slack alerts to each stage of the pipeline. 
The initial build stage will create the initial slack message. Subsequent stages will record success or failure as comments on that ticket.
=> feat: Pipeline slack alerts

.github/workflows/create-release.yml
Update following deprecation
See https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#migration
=> ci: update release please gh action

environment-pipelines/buildspec-apply.yml, environment-pipelines/buildspec-plan.yml, environment-pipelines/buildspec.yml, environment-pipelines/codebuild.tf, environment-pipelines/codepipeline.tf, environment-pipelines/iam.tf, environment-pipelines/locals.tf, environment-pipelines/outputs.tf, environment-pipelines/tests/unit.tftest.hcl, environment-pipelines/variables.tf
This is a breaking change as it takes in structural changes in the configuration files.
Upgrade Path:
1. Create a new file called platform-config.yml
2. Add a key-value pair `application: <application-name>` to the top of the file (replacing `<application-name>` with the name of your application.
3. Copy the content of extensions.yml into platform-config.yml under the key `extensions`
4. Copy the content of pipelines.yml into platform-config.yml 
5. Rename the top level key "codebases" that came from pipelines.yml to "codebase_pipelines"
6. If you are upgrading a legacy project (i.e. digital-workspace) add this line to the top of the "platform-config.yml" file: `legacy_project: true`
=> feat!: New config file and support for multiple pipelines

environment-pipelines/iam.tf
Add missing IAM permissions for modifying the database in the environment pipeline
=> fix: Missing IAM permissions for pipeline to modify database

opensearch/e2e-tests/e2e.tftest.hcl, s3/e2e-tests/e2e.tftest.hcl, vpc/e2e-tests/e2e.tftest.hcl, vpc/main.tf
Fixes for failing end to end terraform tests
=> fix: DBTP-1166 - Fix failing e2e tests

environment-pipelines/codebuild.tf, environment-pipelines/iam.tf
Added IAM permissions to grant pipeline access to make changes required by checkov changes.
=> fix: DBTP-972 Add IAM Permissions for Pipeline Changes

environment-pipelines/buildspec-install-build-tools.yml, environment-pipelines/iam.tf
Adds a permission that is causing errors in the pipeline and adds in a missing quote in the buildspec
=> fix: Fix missing quote and missing permission

elasticache-redis/locals.tf
https://uktrade.atlassian.net/browse/DBTP-1355
=> chore(!): remove redis 6.0 and earlier

s3/main.tf, s3/tests/unit.tftest.hcl
This pull request is a symptom of us not running things all the way through to `prod`.
=> fix: DBTP-1398 Correct prod domain name for static content S3 buckets

s3/main.tf, s3/tests/unit.tftest.hcl
There was more to this than I realised in my previous attempt at fixing it.
This has been tested via a manual `terraform apply`.
=> fix: DBTP-1398 Correct prod domain name for static content S3 buckets (2nd pass)

postgres/database-dump/locals.tf, postgres/database-dump/main.tf, postgres/database-dump/tests/unit.tftest.hcl, postgres/database-load/locals.tf, postgres/database-load/main.tf, postgres/database-load/tests/unit.tftest.hcl
This PR fixes some issues picked up by checkov
=> fix: Tighten ECR permissions

.tool-versions, environment-pipelines/iam.tf
Addresses issue:[DBTP-1435]( https://uktrade.atlassian.net/browse/DBTP-1435)
- We've tested this by following the steps to reproduce on the ticket
[DBTP-1435]: https://uktrade.atlassian.net/browse/DBTP-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1435 Allow environment pipeline to update assume role policy on shared s3 role

environment-pipelines/iam.tf
Add missing load balancer permission to the environment pipelines
=> fix: Add missing load balancer permission

extensions/locals.tf, extensions/main.tf, extensions/tests/unit.tftest.hcl
Addresses https://uktrade.atlassian.net/browse/DBTP-1454.
Parameter before apply with updated `terraform-platform-modules`…
Parameter after apply with updated `terraform-platform-modules`…
=> fix: DBTP-1454 Limit addons parameter to current environment

environment-pipelines/iam.tf, environment-pipelines/tests/unit.tftest.hcl
This reverts commit 00babbd4e00ba7c0820361b4b3aa7720fa82cc6d.
=> fix: Revert "fix: Environment pipelines given ECS permissions for Database..."

environment-pipelines/iam.tf
Addresses [DBTP-1534](https://uktrade.atlassian.net/browse/DBTP-1534)
---
[DBTP-1534]: https://uktrade.atlassian.net/browse/DBTP-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1534 Add S3MigrationRole to the resources allowed to add policies and roles

cdn/locals.tf, cdn/main.tf, cdn/tests/unit.tftest.hcl, cdn/variables.tf
Combine branch DBTP-1434 into DBTP-1433, so regression test can be applied to both changes
=> Dbtp 1434 cdn cache policy

environment-pipelines/iam.tf, environment-pipelines/tests/unit.tftest.hcl
Addresses https://uktrade.atlassian.net/browse/DBTP-1694
---
=> fix: DBTP-1694 - Fix policy issues

codebase-pipelines/buildspec-images.yml, codebase-pipelines/codebuild.tf, codebase-pipelines/tests/unit.tftest.hcl
Addresses https://uktrade.atlassian.net/browse/DBTP-1736
---
=> fix: DBTP-1736 - Add custom slack channel id to image build project

codebase-pipelines/buildspec-deploy.yml
Addresses https://uktrade.atlassian.net/browse/DBTP-1786
Fix hardcoded service name in deploy script
---
=> fix: DBTP-1786 - Use service environment variable to get task count

README.md
Noticed while working on [DBTP-1700](https://uktrade.atlassian.net/browse/DBTP-1700).
---
[DBTP-1700]: https://uktrade.atlassian.net/browse/DBTP-1700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: DBTP-1700 Correct Postgres example in README.md

codebase-pipelines/codepipeline.tf, codebase-pipelines/tests/unit.tftest.hcl, codebase-pipelines/variables.tf, extensions/locals.tf
Addresses [DBTP-1788](https://uktrade.atlassian.net/browse/DBTP-1788)
Please add any relevant context for you pull request here, or delete this if none needed.
---
[DBTP-1788]: https://uktrade.atlassian.net/browse/DBTP-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: DBTP-1788 Add deploy_repository key

codebase-pipelines/codepipeline.tf, codebase-pipelines/tests/unit.tftest.hcl, codebase-pipelines/variables.tf
Addresses https://uktrade.atlassian.net/browse/DBTP-1896
Related PRs
- https://github.com/uktrade/platform-tools/pull/814
- https://github.com/uktrade/platform-documentation/pull/544
---
=> feat: Implement deploy repository branch variable (DBTP-1896)

extensions/main.tf
…ut in AWS
Addresses https://uktrade.atlassian.net/browse/DBTP-<ticket>.
Please add any relevant context for you pull request here, or delete this if none needed.
---
=> fix: Update DD_APP_KEY and DD_API_KEY variable names (DBTP-1879)
