- application-load-balancer/locals.tf
When configuring additional service, eg apis, additional web services in Prod, the autogenerated internal address is incorrectly adding a prod subdomain.  This checks if deploying to prod and adjusts the name.
> fix: DBTP-951 add prod check for additional address list

- opensearch/locals.tf
- opensearch/main.tf
When deploying Opensearch on any instance larger than small, you need to specify the NO_ROLLBACK option in auto tune.  This option has been added to fix this.
> fix: dbtp-971 add rollback option for HA OS

- postgres/locals.tf
- postgres/tests/unit.tftest.hcl
- Update the RDS module default value for RDS instance volume size
> fix: add default volume size for rds local variable

- environment-pipelines/buildspec-plan.yml
- environment-pipelines/iam.tf
- environment-pipelines/locals.tf
- environment-pipelines/stage_config.yml
- environment-pipelines/tests/unit.tftest.hcl
This adds in permissions and pre-requisites for the `platform-helper copilot make-addons` to run in the pipeline. This required a `copilot env init` to ensure the copilot parameter store config is in place.
> feat: Make ``platform-helper copilot make-addons` run in the pipeline

- .checkov.baseline
- application-load-balancer/main.tf
- elasticache-redis/main.tf
- elasticache-redis/tests/unit.tftest.hcl
Because @WillGibson accidentally merged it with the breaking change indicator still there :-(
> fix: Replay DBTP-944 remove "_ENDPOINT" from elasticache redis ssm parameter endpoint

- extensions/main.tf
Tests were broken revealing a misconfiguration in the extensions module when it configures the cdn module.
> fix: Fixed extensions module that was broken on the cdn declaration

- postgres/lambda.tf
[DBTP-1068 Read only postgres user created before application user](https://uktrade.atlassian.net/browse/DBTP-1068)
> fix: make readonly lambda invocation depend on app user invocation

- extensions/plans.yml
The prometheus-policy is a service addon, therefore not managed by terrraform.  We just need a `prometheus-policy` type adding to plans.yml to allow the terraform to run without errors.
> fix: add  prometheus-policy to plans.yml

- environment-pipelines/buildspec-plan.yml
- environment-pipelines/locals.tf
- environment-pipelines/tests/unit.tftest.hcl
Because we need to use the `terraform-platform-modules` `main` branch for the regression tests.
> fix: Don't generate environment Terraform manifest for demodjango toolspr

- environment-pipelines/buildspec-apply.yml
- environment-pipelines/buildspec-plan.yml
- environment-pipelines/locals.tf
- environment-pipelines/tests/unit.tftest.hcl
Work done to pass entire build folder from plan stage to apply stage in order to:
- transfer the plan file properly
- transfer other built artifacts such as the lambda zip files.
> fix: DBTP-1104 Ensure Terraform plan resources are available during apply stage.

- environment-pipelines/buildspec-apply.yml
- environment-pipelines/buildspec.yml
We do not need to run the copilot commands in the pipelines as they will have been run during the initial deployment of the environments. Only the terraform apply is relevant in the new environment pipelines.
> feat: Removing all copilot commands from the terraform pipelines

- environment-pipelines/iam.tf
- environment-pipelines/tests/unit.tftest.hcl
Grants permissions via IAM for the service account used to run pipelines to create/destroy IAM roles via Terraform
> fix: DBTP-1128 Allow Pipeline Account to Create IAM Roles

- s3/e2e-tests/e2e.tftest.hcl
- s3/main.tf
The account id is different when the E2E tests are running in CodeBuild.
Change the S3 e2e tests to use caller identity for the account id instead of a hard coded value.
> test: DBTP-1045 - Remove hardcoded account id from S3 e2e test

- environment-pipelines/codepipeline.tf
When trigger_on_push is set to true, it sets the DetectChanges in the environment pipeline to true, which causes a default trigger to be created for the pipeline, as this trigger is created outside of terraform it is not part of the state and terraform will attempt to delete it on each run. This issue is not experienced if trigger_on_push is set to false as the default trigger isn't created.
The only use of DetectChanges is in a single location - so instructing Terraform to ignore the trigger resolves the issue with no further impact. Attempting to recreate the trigger in terraform was unsuccessful and wouldn't match the default trigger.
This issue is discussed [here](https://github.com/hashicorp/terraform-provider-aws/issues/38409).
> fix: DBTP-1143 Prevent Trigger Being Deleted on TF Plan/Apply

- environment-pipelines/buildspec-plan.yml
- environment-pipelines/iam.tf
- environment-pipelines/tests/unit.tftest.hcl
This change has two components
- Updated IAM permissions to allow the service account used to run pipelines to retrieve pipeline details, retrieve pipeline execution details; and to stop pipeline executions
- Add a command to the terraform plan pipeline stage to get any instances of InProgress Approval stages and to stop the execution of those pipeline instances before running the terraform plan.
> fix: DBTP-1149 - Cancel Outstanding Approval Requests before Performing a Terraform Plan

- application-load-balancer/tests/unit.tftest.hcl
- application-load-balancer/variables.tf
- cdn/tests/unit.tftest.hcl
- cdn/variables.tf
Added Validation to Variables.tf for both CDN and ALB modules to check the length of the domain name. This will throw the error 
`Error: Invalid value for variable
│
│   on ../../../../terraform-platform-modules/extensions/main.tf line 64, in module "alb":
│   64:   config = each.value
│     ├────────────────
│     │ var.config.cdn_domains_list is map of list of string with 1 element
│
│ Items in cdn_domains_list should be between 3 and 63 characters long.
│
│ This was checked by the validation rule at ../../../../terraform-platform-modules/application-load-balancer/variables.tf:21,3-13.`
If the domain name is > 63 characters or < 3 characters as per guidance [here](https://www.gov.uk/guidance/choose-your-govuk-domain-name?step-by-step-nav=5a9309a3-9a80-4faa-b24f-1797023e897f)
> fix: DBTP-1169 Added Validation for Domain Name Length

- application-load-balancer/tests/unit.tftest.hcl
- application-load-balancer/variables.tf
- cdn/tests/unit.tftest.hcl
- cdn/variables.tf
The validation on the optional cdn_domains_list variable used in cdn and application-load-balancer modules was causing an error when no domain lists were specified.
This change fixes the validation in the case of a null list.
> fix: cdn and application-load-balancer modules "null value cannot be used as the collection in a 'for' expression" error

- environment-pipelines/buildspec-plan.yml
- environment-pipelines/buildspec-trigger.yml
The environment codebuild job failed because the notify command run during POST_BUILD in plan and trigger phases could not interpret the injected variable.
This change corrects the command by removing surplus double quotes.
> fix: buildspec notify command ADDITIONAL_OPTIONS injection

- opensearch/locals.tf
- opensearch/main.tf
- opensearch/tests/unit.tftest.hcl
- opensearch/variables.tf
Digital Workspace OpenSearch integration cannot cope with urlencoded passwords, and also breaks when certain characters are present but not encoded (e.g. @)
This change allows teams to:
- disable urlencoding using the "urlencode_password" parameter
- define their own set of special characters using the "password_special_characters" parameter.
In addition I have defaulted the set of special characters to "-_!.~$&'()*+,;=" as these are considered safe if unencoded in the password.
> fix: DBTP-1346 Add special characters & urlencode options for OpenSearch passwords

- environment-pipelines/codepipeline.tf
- environment-pipelines/tests/unit.tftest.hcl
Explicitly add a trigger block with the source branch to the environment pipeline.
> fix: DBTP-1366 - Force environment pipeline to trigger on correct branch

- environment-pipelines/buildspec-apply.yml
- environment-pipelines/iam.tf
- environment-pipelines/locals.tf
- environment-pipelines/tests/unit.tftest.hcl
The way the AWS profile was accessed in the `platform-helper environment generate` command changed in [this PR](https://github.com/uktrade/platform-tools/pull/568)
We now need a named AWS_PROFILE in the environment pipeline apply stage rather than using the inherited CodeBuild permissions.
> fix: DBTP-1394 - Fix platform-helper environment generate command in environment pipeline apply stage

- s3/main.tf
The prod domain suffix is different to non prod environments
> fix: DBTP-1396 - Fix S3 domain name for prod environments

- s3/main.tf
- s3/tests/unit.tftest.hcl
I guess the question is, were the tests right, or was the code right?
> test: Remove redundant assertions for defaults in S3 unit tests

- postgres/database-dump/locals.tf
- postgres/database-load/locals.tf
Currently many databases are just called `database` in the platform config file, so for fft this would have been `prod-database-dump`, which isn't unique enough, this change makes it `fft-prod-database-dump`.
> fix: bucket name clashes

- environment-pipelines/iam.tf
Addresses https://uktrade.atlassian.net/browse/DBTP-1524
Add permission for pipeline to read cloudformation export
---
> fix: Add missing environment pipeline permission

- CHANGELOG.md
Addresses [DBTP-<ticket>](https://uktrade.atlassian.net/browse/DBTP-<ticket>)
Please add any relevant context for you pull request here, or delete this if none needed.
---
> chore: Add upgrade path info for terraform platform modules release version 6

- monitoring/main.tf
- monitoring/tests/unit.tftest.hcl
Add tables to environment CloudWatch dashboards to show deployed application and sidecar images
---
> feat: Add table to CloudWatch dashboard to show deployed images

- environment-pipelines/iam.tf
Addresses [DBTP-1791](https://uktrade.atlassian.net/browse/DBTP-1791).
Because the end to end tests failed.
---
[Regression test run](https://763451185160-2qjkzelg.eu-west-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/pull-request-end-to-end-tests/executions/65425bab-934b-4133-8876-349106e9a768/visualization?region=eu-west-2).
[DBTP-1791]: https://uktrade.atlassian.net/browse/DBTP-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: DBTP-1991 Allow environment pipeline to adjust ElastiCache replication count

- extensions/locals.tf
The plan was being looked up with "elasticache-redis" but we specify the type as just "redis". This was causing the plan to not be found and terraform fall back to the defaults.
We specify the tiny plan in demodjango
```
demodjango-redis:
type: redis
environments:
"*":
engine: "7.1"
plan: tiny
apply_immediately: true
```
Which should be:
```
tiny:
replicas: 0
instance: cache.t4g.small
```
But terraform is trying to do:
---
> fix: Redis plans being ignored

- elasticache-redis/main.tf
- elasticache-redis/tests/unit.tftest.hcl
- monitoring/main.tf
- opensearch/main.tf
- opensearch/tests/unit.tftest.hcl
- postgres/lambda.tf
- postgres/tests/unit.tftest.hcl
Addresses https://uktrade.atlassian.net/browse/DBTP-1563
Fix these warnings every time we run a terraform command:
```
│ Warning: Argument is deprecated
│ 
│   with module.extensions.module.elasticache-redis["demodjango-redis"].aws_iam_role.conduit_ecs_task_role,
│   on .terraform/modules/extensions/elasticache-redis/main.tf line 88, in resource "aws_iam_role" "conduit_ecs_task_role":
│   88: resource "aws_iam_role" "conduit_ecs_task_role" {
```
---
> fix: DBTP-1563 - Use iam_role_policy instead of deprecated inline policies

- vpc/main.tf
- vpc/tests/unit.tftest.hcl
Ad-hoc quick fix
The [demodjango-deploy/copilot/{service}/overrides/cfn.patches.yml](https://github.com/uktrade/demodjango-deploy/blob/fe0daac6e5d801c3bc6bcea7f2efc99c2f3bb0d5/copilot/web/overrides/cfn.patches.yml#L26) file grants the service access to the SSM params that have the tag:
```
copilot-application': '__all__'
```
We need to add that tag to the EGRESS_IP SSM param in order for the copilot/{service}/manifest.yml to use the SSM parameter.
Each time an environment gets re-provisoned it was wiping the manually added tag and this breaks the codebase pipeline as thew web service depends on the EGRESS_IP SSM param
[Deployment failure logs](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters/demodjango-tony/services/demodjango-tony-web-Service-DdRQaBu2AQnW/tasks/af7a086619ba4fa0a03 …
> fix: Fix missing tag for SSM parameter EGRESS_IP

- environment-pipelines/iam.tf
Addresses https://uktrade.atlassian.net/browse/DBTP-1972 - an issue that was raised in platform-requests.
There is a missing permission in the codeconnection resource within `environment-pipelines` that prevented one of the service's environment pipeline from running successfully after they had deployed the data copy pipeline to their account. This ticket simply adds that permission in
We have manually tested this through adding the permission via the IAM policy console and noted a successful pipeline execution
---
> fix: Add missing action to environment pipelines (DBTP-1972)
